import express from "express";
import { UserController } from "../controllers/user.controller";
import { UserValidation } from "../validations/user.validation";
import { validate } from "../middlewares/validation.middleware";
import { authenticate } from "../middlewares/authentication.middleware";
const router = express.Router();
router.post("/sign-up", UserValidation.signUp, validate, UserController.signUp);
router.post("/sign-in", UserValidation.signIn, validate, UserController.signIn);
router.put("/logout", authenticate.authUser, UserController.logOut);
router.get("/self", authenticate.authUser, UserController.selfUser);
export default router;
